---
- name: import and trust elasticsearch rpm gpg key
  rpm_key: key="https://packages.elasticsearch.org/GPG-KEY-elasticsearch"

- name: configure elasticsearch repo
  copy: src="elasticsearch-1.5.repo" dest="/etc/yum.repos.d/elasticsearch-1.5.repo"
        owner=root group=root mode=0444

- name: upload logstash and kibana (not in repos)
  get_url: url="{{ item }}" dest="/tmp/"
  with_items:
  - "https://download.elastic.co/kibana/kibana/kibana-4.0.2-linux-x64.tar.gz"
  - "https://download.elastic.co/logstash/logstash/packages/centos/logstash-1.4.2-1_2c0f5a1.noarch.rpm"

- name: install elasticsearch and logstash
  yum: name="{{ item }}" state=present
  with_items:
  - java-1.7.0-openjdk
  - elasticsearch
  - "/tmp/logstash-1.4.2-1_2c0f5a1.noarch.rpm"
  - supervisor

- name: configure elasticsearch
  template: src="elasticsearch.yml" dest="/etc/elasticsearch/elasticsearch.yml"
            owner=root group=root mode=0444
  notify:
  - restart elasticsearch

- name: elasticsearch started and enabled
  service: name=elasticsearch state=started enabled=yes

- name: extract kibana
  unarchive: src="/tmp/kibana-4.0.2-linux-x64.tar.gz" dest="/opt" copy=no

- name: configure kibana
  template: src="kibana.yml" dest="/opt/kibana-4.0.2-linux-x64/kibana.yml"
            owner=root group=root mode=0444

- name: configure supervisord (run kibana)
  template: src="supervisord.conf" dest="/etc/supervisord.conf" backup=yes
  notify:
  - restart supervisord

- name: supervisord started and enabled
  service: name=supervisord state=started enabled=yes

- name: configure logstash
  template: src="{{ item }}" dest="/etc/logstash/conf.d/"
  with_items:
  - "01-elasticsearch-storage.conf"
  - "10-syslog-input.conf"
  notify:
  - restart logstash

- name: logstash started and enabled
  service: name=logstash state=started enabled=yes
