---
- name: slurmdbd packages are installed
  yum: name={{item}} state=present
  with_items:
  - slurm-munge
  - slurm-plugins
  - munge
  - slurm-slurmdbd
  - slurm-sql
  - MySQL-python
  - mariadb-server
  - mariadb-devel

- name: mysqld is running
  service: name=mariadb state=started

- name: slurm user exists
  user: name=slurm state=present

- name: slurm mysqld user is configured
  mysql_user: 
    name=slurm 
    password={{slurmdbd_password}} 
    priv="slurm_acct_db.*:ALL"
    login_host={{mysql_host}} 
    login_user={{mysql_admin}}
    

- name: slurmdbd service is configured
  template: src=slurmdbd.conf dest=/etc/slurm/slurmdbd.conf 
  notify:
  - slurmdbd is restarted

- name: slurmdbd is started and enabled
  service: name=slurmdbd state=started enabled=yes
